### ISSUE TITLE
LFS:Put connexion refused

### ISSUE THREAD

**Issue by moriamoria** [git-lfs/lfs-test-server#76] opened 2018-03-07 11:06 UTC
Hello,

I like help on using lfs-test-server.

When I try to push lfs files, I got  connection refused. I see inside lfs-test-server request 

I have define a new user (user:matthieu password:matthieu) But I dont know how to set this user to LFS client configuration.

Can anyone help me ?

Regards

Matthieu

result from lfs-test-server 👍 

 [server.go:240]: request_id=8324f5a1-5165-8e5c-ec1b-c18602b87e44 method=POST url=/objects/batch status=200
2018-03-07T10:50:41Z LFRCRA02426 lfs[15276] [server.go:240]: method=POST url=/objects/batch status=200 request_id=6b6f8cc8-0562-6764-16c3-54e220dd3e23
2018-03-07T10:50:44Z LFRCRA02426 lfs[15276] [server.go:240]: method=POST url=/objects/batch status=200 request_id=2ec2b5e3-1647-7ee4-5706-fdeca0199157
2018-03-07T10:50:47Z LFRCRA02426 lfs[15276] [server.go:240]: method=POST url=/objects/batch status=200 request_id=f000cd28-56eb-9038-2b80-c59a42ef1255
2018-03-07T10:50:50Z LFRCRA02426 lfs[15276] [server.go:240]: method=POST url=/objects/batch status=200 request_id=57f36a43-f031-d552-1939-7b4209f6d0f1
2018-03-07T10:50:53Z LFRCRA02426 lfs[15276] [server.go:240]: method=POST url=/objects/batch status=200 request_id=0154e339-3cbf-7c24-32f3-946e2291a231
2018-03-07T10:50:56Z LFRCRA02426 lfs[15276] [server.go:240]: url=/objects/batch status=200 request_id=6a67820e-a87a-8db8-f2d3-505ccea8bb04 method=POST

LFS: Put http://localhost/objects/124ed7cb81447c8689ad5c5956ef913155612c285886dcdcad75db081ac6b30e: dial tcp [::1]:80: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.

config file :

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	ignorecase = true
[lfs]
	url = "http://localhost:8080/"
[remote "remoteT5"]
	url = z:/Git/t5/
	fetch = +refs/heads/*:refs/remotes/remoteT5/*
[lfs "http://localhost:8080/"]
	locksverify = false
	access = basic

**Comment by ttaylorr** [comment] 2018-03-19 22:30
Hi @moriamoria, thanks for opening this issue. You can configure the Git LFS client to use a given username and password via the following:

https://github.com/git-lfs/git-lfs/blob/master/docs/api/authentication.md#specified-in-url

As for the connection issue, I believe that this is a duplicate of https://github.com/git-lfs/git-lfs/issues/2904, so I am going to close this for now and move discussion there.

If the above does not solve the authentication issue, please do not hesitate to let me know here, and I'd be more than happy to dive in and help. Thanks!

**Closed by ttaylorr** 2018-03-19 22:30 UTC
